#if !defined(AFX_HANDLEOCR_H__56E219F1_688B_428C_8395_1132DB528D06__INCLUDED_)
#define AFX_HANDLEOCR_H__56E219F1_688B_428C_8395_1132DB528D06__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CHandleOCR wrapper class

class CHandleOCR : public CWnd
{
protected:
	DECLARE_DYNCREATE(CHandleOCR)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x1b26a205, 0xf568, 0x4205, { 0x87, 0xb, 0x49, 0x3d, 0x6f, 0xf2, 0xd3, 0xfe } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	BOOL Compare(LPCTSTR GiroData);
	BOOL InsertData();
	BOOL DeleteData();
	void ClearData(LPCTSTR GiroData);
	void ClearAll();
	void SaveBMP(LPCTSTR strFileName);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_HANDLEOCR_H__56E219F1_688B_428C_8395_1132DB528D06__INCLUDED_)
