// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "handleocr.h"

/////////////////////////////////////////////////////////////////////////////
// CHandleOCR

IMPLEMENT_DYNCREATE(CHandleOCR, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CHandleOCR properties

/////////////////////////////////////////////////////////////////////////////
// CHandleOCR operations

BOOL CHandleOCR::Compare(LPCTSTR GiroData)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		GiroData);
	return result;
}

BOOL CHandleOCR::InsertData()
{
	BOOL result;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CHandleOCR::DeleteData()
{
	BOOL result;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CHandleOCR::ClearData(LPCTSTR GiroData)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 GiroData);
}

void CHandleOCR::ClearAll()
{
	InvokeHelper(0x5, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CHandleOCR::SaveBMP(LPCTSTR strFileName)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strFileName);
}

void CHandleOCR::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
