#if !defined(AFX_NHICCM_H__AED9AD6D_8F74_4FD2_8CE0_B09079595466__INCLUDED_)
#define AFX_NHICCM_H__AED9AD6D_8F74_4FD2_8CE0_B09079595466__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CNHICCM wrapper class

class CNHICCM : public CWnd
{
protected:
	DECLARE_DYNCREATE(CNHICCM)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xe38bac66, 0xe825, 0x46e2, { 0x9a, 0x8a, 0xe0, 0x96, 0x46, 0x64, 0x8b, 0x4e } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long OpenConnection(long WaitSec);
	long CloseConnection();
	long ICSendData(long ProtocolID, short nCmdType, LPCTSTR szICSendData, long WaitSec);
	CString ICRecvData();
	long ICSendData2(long ProtocolID, short nCmdType, short nParam1, short nParam2, LPCTSTR szICSendData, long WaitSec);
	long ISOInSend(long ProtocolID, LPCTSTR szICSendData, long WaitSec);
	long ISOOutSend(long ProtocolID, LPCTSTR szICSendData, long WaitSec);
	long ICCMInitialize(long WaitSec);
	CString ICCMGetErrorCode();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_NHICCM_H__AED9AD6D_8F74_4FD2_8CE0_B09079595466__INCLUDED_)
