// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "nhiccm.h"

/////////////////////////////////////////////////////////////////////////////
// CNHICCM

IMPLEMENT_DYNCREATE(CNHICCM, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CNHICCM properties

/////////////////////////////////////////////////////////////////////////////
// CNHICCM operations

long CNHICCM::OpenConnection(long WaitSec)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		WaitSec);
	return result;
}

long CNHICCM::CloseConnection()
{
	long result;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHICCM::ICSendData(long ProtocolID, short nCmdType, LPCTSTR szICSendData, long WaitSec)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I2 VTS_BSTR VTS_I4;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		ProtocolID, nCmdType, szICSendData, WaitSec);
	return result;
}

CString CNHICCM::ICRecvData()
{
	CString result;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

long CNHICCM::ICSendData2(long ProtocolID, short nCmdType, short nParam1, short nParam2, LPCTSTR szICSendData, long WaitSec)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I2 VTS_I2 VTS_I2 VTS_BSTR VTS_I4;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		ProtocolID, nCmdType, nParam1, nParam2, szICSendData, WaitSec);
	return result;
}

long CNHICCM::ISOInSend(long ProtocolID, LPCTSTR szICSendData, long WaitSec)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR VTS_I4;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		ProtocolID, szICSendData, WaitSec);
	return result;
}

long CNHICCM::ISOOutSend(long ProtocolID, LPCTSTR szICSendData, long WaitSec)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR VTS_I4;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		ProtocolID, szICSendData, WaitSec);
	return result;
}

long CNHICCM::ICCMInitialize(long WaitSec)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		WaitSec);
	return result;
}

CString CNHICCM::ICCMGetErrorCode()
{
	CString result;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CNHICCM::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
