
#ifndef _ISATM_ERR_H
#define _ISATM_ERR_H

#define Err_HA_INVALID_ARGUMENT		-101
#define Err_HANDLE_MALLOC_ERROR		-102
#define Err_AUTHFILE_READ			-103
#define Err_AUTHFILE_DECRYPT		-104
#define	Err_RSA_NEW					-105
#define Err_AUTHFILE_DECODE			-106
#define Err_ISALV_INVALID			-107
#define Err_INVALID_DATAFORMAT		-108
#define Err_ISALV_DECODE			-109

#define Err_CTXPATH_IS_NULL			-201
#define Err_HLOAD_CTXPATH_FOPEN_ERROR	-202
#define Err_HLOAD_CH3_ERROR			-203
#define Err_HLOAD_CH4_ERROR			-204
#define Err_HLOAD_SKEY_ERROR		-205
#define Err_HLOAD_IV_ERROR			-206
#define Err_HLOAD_SID_ERROR			-207
#define Err_HLOAD_STATUS_ERROR		-208
#define Err_HLOAD_FLAG_ERROR		-209
#define Err_CTXFILE_DECRYPT_ERROR	-210
#define Err_CTXFILE_ENCRYPT_ERROR	-211
#define Err_CTXFILE_INVALID_STATUS	-212

#define Err_INVALID_ARGUMENT		-301
#define Err_HSTORE_CTXPATH_FOPEN_ERROR	-302
#define Err_HSTORE_CH3_ERROR		-303
#define Err_HSTORE_CH4_ERROR		-304
#define Err_HSTORE_SKEY_ERROR		-305
#define Err_HSTORE_IV_ERROR			-306
#define Err_HSTORE_SID_ERROR		-307
#define Err_HSTORE_STATUS_ERROR		-308
#define Err_HSTORE_FLAG_ERROR		-309
#define Err_HSTORE_FWRITE_ERROR		-310

#define	Err_CH_INVALID_ARGUMENT		-401
#define Err_CH_BUFSIZE_NOT_ENOUGH	-402

#define	Err_CF_INVALID_ARGUMENT		-501
#define Err_CF_INVALID_STATUS		-502
#define Err_CF_TYPE_MISMATCH		-503
#define Err_CF_KEY_EXCHANGE_FAIL	-504

#define Err_CE_INVALID_ARGUMENT		-601
#define Err_CE_INVALID_STATUS		-602
#define Err_CE_BUFSIZE_NOT_ENOUGH	-603
	
#define Err_CD_INVALID_ARGUMENT		-701
#define Err_CD_INVALID_STATUS		-702
#define Err_CD_TYPE_MISMATCH		-703
#define Err_CD_CHALLENGE_MISMATCH	-704
#define Err_CD_MAC_CHECK_ERROR		-705
#define Err_CD_BUFSIZE_NOT_ENOUGH	-706
#define Err_INVALID_COUNT			-707

#define Err_CKI_INVALID_ARGUMENT	-801
#define Err_CKI_INVALID_STATUS		-802
#define Err_CKI_BUFSIZE_NOT_ENOUGH	-803
#define Err_CKU_INVALID_ARGUMENT	-804
#define Err_CKU_LV_LEN_WRONG		-805
#define Err_CKU_TYPE_MISMATCH		-806
#define Err_CKF_INVALID_STATUS		-807
#define Err_CKF_INVALID_ARGUMENT	-808
#define Err_CKF_LV_LEN_WRONG		-809
#define Err_CKF_TYPE_MISMATCH		-810
#define Err_CKU_BUFSIZE_NOT_ENOUGH	-811
#define Err_CEP_INVALID_ARGUMENT	-812

#define Err_FILE_OPEN_ERROR			-901
#define Err_FREAD_ERROR				-902
#define Err_MALLOC_ERROR			-903
#define Err_PUBKEY_ENCRYPT_ERROR	-904
#define Err_PRIVKEY_ENCRYPT_ERROR	-905
#define Err_PRIVKEY_DECRYPT_ERROR	-906
#define Err_PUBKEY_DECRYPT_ERROR	-907
#define Err_GEN_SKIV_ERROR			-908
#define Err_SEED_ENCRYPT_ERROR		-909
#define Err_SEED_DECRYPT_ERROR		-910
#define Err_LOAD_X509_ERROR			-911
#define Err_X509_GET_PUBKEY_ERROR	-912
#define Err_X509_GET_RSA_ERROR		-913
#define Err_X509_GET_SERIAL_ERROR	-914
#define Err_LOAD_SERVER_CERT		-915
#define Err_BASE64DECODE_ERROR		-916
#define Err_BASE64ENCODE_ERROR		-917
#define Err_ISAMSG_SET				-918
#define Err_REMOVE_FILE				-919
#define Err_SERVER_ERROR			-920
#define Err_NOT_INIT				-921
#define Err_UNKNOWN_ERROR			-922

#endif
